// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASmHE4n-Uedu1mhTi9rH2fM1CYeAdyJZk',
    appId: '1:335206650251:web:2b6bd67cac4f67219d5f8e',
    messagingSenderId: '335206650251',
    projectId: 'doitnow-fca79',
    authDomain: 'doitnow-fca79.firebaseapp.com',
    storageBucket: 'doitnow-fca79.firebasestorage.app',
    measurementId: 'G-3JRZPBF8M6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDPbxnw3f-x9gDvj9s_8OerUYWAoQWW_s',
    appId: '1:335206650251:android:3996639d58c50b0e9d5f8e',
    messagingSenderId: '335206650251',
    projectId: 'doitnow-fca79',
    storageBucket: 'doitnow-fca79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVwg4cTJPilKrSj3T_mCL9GlAcpkVnlBI',
    appId: '1:335206650251:ios:b85e90e2d269fde19d5f8e',
    messagingSenderId: '335206650251',
    projectId: 'doitnow-fca79',
    storageBucket: 'doitnow-fca79.firebasestorage.app',
    iosBundleId: 'com.doitnow.doitnowApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVwg4cTJPilKrSj3T_mCL9GlAcpkVnlBI',
    appId: '1:335206650251:ios:b85e90e2d269fde19d5f8e',
    messagingSenderId: '335206650251',
    projectId: 'doitnow-fca79',
    storageBucket: 'doitnow-fca79.firebasestorage.app',
    iosBundleId: 'com.doitnow.doitnowApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASmHE4n-Uedu1mhTi9rH2fM1CYeAdyJZk',
    appId: '1:335206650251:web:02a3a01f5ce17dfa9d5f8e',
    messagingSenderId: '335206650251',
    projectId: 'doitnow-fca79',
    authDomain: 'doitnow-fca79.firebaseapp.com',
    storageBucket: 'doitnow-fca79.firebasestorage.app',
    measurementId: 'G-4LKFPB7HFR',
  );
}
